# Generated by Django 2.2.5 on 2019-09-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_itemorcamento_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
    ]
