# Generated by Django 2.2.5 on 2019-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_itemorcamento_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='codigo_item',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='codigo_orcamento',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='codigo_produto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='codigo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
